import Navbar from "@/components/Navbar"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Toaster } from "@/components/ui/toaster"
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs"
import { cookies } from "next/headers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
   const supabase = createServerComponentClient({ cookies })

   const { data } = await supabase.auth.getSession()

   // if (!data.user) {
   // redirect("/auth")
   // }

   console.log(data)

   return (
      <html lang="en">
         <body className={inter.className}>
            <Navbar />

            <main>{children}</main>

            <Toaster />
         </body>
      </html>
   )
}
